50

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  update-root-path:
+  check-modified-app:
     runs-on: ubuntu-latest
 
     steps:
@@ -67,6 +67,33 @@ jobs:
           else
             echo "This is an unknown event"
           fi
+    
+  clock-gain-deployment:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if root is 'clock-gain' in nest-cli.json
+        id: check-root
+        run: |
+          root=$(jq -r '.root' nest-cli.json)
+          if [[ "$root" != "apps/clock-gain" ]]; then
+            echo "Skipping workflow since root is not 'apps/clock-gain'"
+            exit 78  # Skip the job with a neutral exit code
+          fi
+
+  camped-deployment:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if root is 'camped' in nest-cli.json
+        id: check-root
+        run: |
+          root=$(jq -r '.root' nest-cli.json)
+          if [[ "$root" != "apps/camped" ]]; then
+            echo "Skipping workflow since root is not 'apps/camped'"
+            exit 78  # Skip the job with a neutral exit code
+          fi
+
+
+
       # - name: List Modified Files
       #   run: |
       #     modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
